// src/lib/authErrors.ts
//
// Centralised mapping of raw Supabase Auth errors (or plain strings) into
// friendly, user-facing messages. Keeping this in one place means every auth
// surface (AuthForm, ForgotPassword, ResetPassword, useAuth) presents
// consistent copy and we can tune wording without touching UI components.

import type { AuthError } from "@supabase/supabase-js";

/** Anything we might be handed as an "error". */
type UnknownAuthError = AuthError | Error | string | null | undefined;

/**
 * Well-known Supabase / GoTrue error substrings mapped to friendlier copy.
 * Matching is done case-insensitively on the raw message so we stay resilient
 * to minor wording changes across SDK versions.
 */
const MESSAGE_OVERRIDES: Array<{ match: RegExp; message: string }> = [
  {
    match: /invalid login credentials/i,
    message: "Incorrect email or password. Please try again.",
  },
  {
    match: /email not confirmed/i,
    message:
      "Please confirm your email address first. Check your inbox for the confirmation link.",
  },
  {
    match: /user already registered|already registered|already been registered/i,
    message:
      "An account with this email already exists. Try signing in instead.",
  },
  {
    match: /password should be at least/i,
    message: "Your password is too short. Use at least 6 characters.",
  },
  {
    match: /rate limit|too many requests|for security purposes/i,
    message: "Too many attempts. Please wait a moment and try again.",
  },
  {
    match: /network|failed to fetch/i,
    message:
      "Network error. Please check your connection and try again.",
  },
  {
    match: /popup closed|popup_closed|window closed/i,
    message: "The sign-in window was closed before completing. Please retry.",
  },
  {
    match: /provider is not enabled|oauth provider/i,
    message:
      "Google sign-in isn't available right now. Please try email sign-in.",
  },
  {
    match: /email link is invalid or has expired|token has expired|invalid token/i,
    message: "This link is invalid or has expired. Please request a new one.",
  },
];

/**
 * Convert any auth error into a clean, user-friendly message.
 */
export function getAuthErrorMessage(error: UnknownAuthError): string {
  if (!error) {
    return "Something went wrong. Please try again.";
  }

  const raw =
    typeof error === "string"
      ? error
      : error.message || "Something went wrong. Please try again.";

  const override = MESSAGE_OVERRIDES.find((entry) => entry.match.test(raw));
  if (override) {
    return override.message;
  }

  return raw;
}

export default getAuthErrorMessage;

// ── Auto-generated by KrossBuild named-export gate ──
// These bindings were imported elsewhere but missing here. Preserved blocks
// are recovered verbatim from the prior version of this file (sticky export
// invariant); unknown names are safe stubs. Replace stubs with real logic.
export const mapAuthError: any = undefined;
