// src/components/campaign/campaignFormSchema.ts

import { z } from "zod";
import { CAMPAIGN_CATEGORIES } from "@/types/campaign";

// ── Default values for the multi‑step campaign form ────────────────────────
export const CAMPAIGN_FORM_DEFAULTS = {
  title: "",
  description: "",
  category: "",
  targetAudience: "",
  longDescription: "",
  story: "",
  coverImageUrl: "",
  mediaUrls: [""],
  goalAmount: 0,
  currency: "USD",
  deadline: "",
  donorWallEnabled: true,
  accountHolderName: "",
  bankName: "",
  accountNumber: "",
  routingNumber: "",
  swiftBic: "",
  country: "",
};

// ── Zod schema with per‑step refinement ────────────────────────────────────
export const campaignFormSchema = z
  .object({
    title: z.string().min(3, "Title must be at least 3 characters"),
    description: z
      .string()
      .min(10, "Description must be at least 10 characters")
      .max(160, "Short description cannot exceed 160 characters"),
    category: z
      .string()
      .refine((val) => CAMPAIGN_CATEGORIES.includes(val as any), {
        message: "Please select a valid category",
      }),
    targetAudience: z.string().optional(),
    longDescription: z.string().optional(),
    story: z.string().optional(),
    coverImageUrl: z.string().url().optional().or(z.literal("")),
    mediaUrls: z.array(z.string()).optional(),
    goalAmount: z.number().positive("Goal amount must be greater than 0"),
    currency: z.string().min(1),
    deadline: z.string().min(1, "Deadline is required"),
    donorWallEnabled: z.boolean(),
    accountHolderName: z.string().min(1, "Account holder name is required"),
    bankName: z.string().min(1, "Bank name is required"),
    accountNumber: z.string().min(1, "Account number is required"),
    routingNumber: z.string().optional(),
    swiftBic: z.string().optional(),
    country: z.string().min(1, "Country is required"),
  })
  .refine(
    (data) => {
      // If category is provided, it must be one of the allowed values
      if (data.category && !CAMPAIGN_CATEGORIES.includes(data.category as any)) {
        return false;
      }
      return true;
    },
    {
      message: "Please select a valid category",
      path: ["category"],
    }
  );

// ── Step definitions used by the stepper and per‑step validation ───────────
export const CAMPAIGN_FORM_STEPS = [
  {
    id: "basicInfo",
    title: "Basic Information",
    description: "Give your campaign a name, category, and a short pitch.",
    fields: ["title", "description", "category", "targetAudience"],
  },
  {
    id: "details",
    title: "Rich Details",
    description: "Tell your story and add media to engage supporters.",
    fields: [
      "longDescription",
      "story",
      "coverImageUrl",
      "mediaUrls",
    ],
  },
  {
    id: "goalDeadline",
    title: "Goal & Deadline",
    description: "Set your fundraising target and closing date.",
    fields: ["goalAmount", "currency", "deadline", "donorWallEnabled"],
  },
  {
    id: "bankDetails",
    title: "Bank Details",
    description:
      "Enter the bank account where funds should be disbursed. All data is encrypted.",
    fields: [
      "accountHolderName",
      "bankName",
      "accountNumber",
      "routingNumber",
      "swiftBic",
      "country",
    ],
  },
];

// ── Auto-generated by KrossBuild named-export gate ──
// These bindings were imported elsewhere but missing here. Preserved blocks
// are recovered verbatim from the prior version of this file (sticky export
// invariant); unknown names are safe stubs. Replace stubs with real logic.
// [sticky-export] CAMPAIGN_CATEGORIES — recovered from prior version
export const CAMPAIGN_CATEGORIES = [
  "Community",
  "Education",
  "Environment",
  "Health",
  "Animals",
  "Emergencies",
  "Arts & Culture",
  "Sports",
  "Technology",
  "Other",
] as const;
// [sticky-export] CURRENCY_OPTIONS — recovered from prior version
export const CURRENCY_OPTIONS = [
  { value: "USD", label: "USD ($)", symbol: "$" },
  { value: "EUR", label: "EUR (\u20ac)", symbol: "\u20ac" },
  { value: "GBP", label: "GBP (\u00a3)", symbol: "\u00a3" },
  { value: "CAD", label: "CAD ($)", symbol: "$" },
  { value: "AUD", label: "AUD ($)", symbol: "$" },
  { value: "INR", label: "INR (\u20b9)", symbol: "\u20b9" },
] as const;
// [sticky-export] COUNTRY_OPTIONS — recovered from prior version
export const COUNTRY_OPTIONS = [
  "United States",
  "Canada",
  "United Kingdom",
  "Australia",
  "Germany",
  "France",
  "India",
  "Other",
] as const;
