// src/types/campaign.ts

// Catalog of campaign categories used in creation wizard and explore filters.
export const CAMPAIGN_CATEGORIES = [
  "Education",
  "Health",
  "Environment",
  "Technology",
  "Community",
  "Arts",
  "Sports",
  "Emergency",
  "Faith",
  "Other",
] as const;

// Filters allow the user to pick any category or view all.
export const CATEGORY_FILTERS = CAMPAIGN_CATEGORIES;

/**
 * Campaign statuses – maps to the database enum.
 */
export type CampaignStatus = "draft" | "active" | "paused" | "closed";

/**
 * Shape of a single campaign row as returned by the backend mapper.
 * (Also used by createCampaign and updateCampaign service functions.)
 */
export interface Campaign {
  id: string;
  title: string;
  description: string;
  category: string;
  targetAudience?: string;
  longDescription?: string;
  story?: string;
  coverImageUrl?: string;
  mediaUrls: string[];
  goalAmount: number;
  currency: string;
  deadline: string;
  donorWallEnabled: boolean;
  raisedAmount: number;
  backersCount: number;
  status: CampaignStatus;
  creatorId?: string;
  created_at?: string;
  updated_at?: string;
}

/**
 * Form values for the multi-step creation / edit wizard.
 * Mirrors the fields of the campaigns table, plus secure bank details
 * that are persisted via the dedicated bank-details edge function.
 */
export interface CampaignFormValues {
  title: string;
  description: string;
  category: string;
  targetAudience: string;
  longDescription: string;
  story: string;
  coverImageUrl: string;
  mediaUrls: string[];
  goalAmount: number;
  currency: string;
  deadline: string;
  donorWallEnabled: boolean;

  // Bank details (only sent to the secure edge function, never stored in the client)
  accountHolderName: string;
  bankName: string;
  accountNumber: string;
  routingNumber?: string;
  swiftBic?: string;
  country: string;
}

/** Utility: derive progress percentage (0‑100), guard against 0 goal. */
export function campaignProgress(campaign: Campaign): number {
  if (!campaign.goalAmount || campaign.goalAmount <= 0) return 0;
  return Math.min(
    100,
    Math.round((campaign.raisedAmount / campaign.goalAmount) * 100)
  );
}

/** Maps a raw database row to the Campaign interface. */
export function mapRowToCampaign(row: Record<string, unknown>): Campaign {
  return {
    id: String(row.id ?? ""),
    title: String(row.title ?? ""),
    description: String(row.description ?? ""),
    category: String(row.category ?? ""),
    targetAudience: row.targetAudience ? String(row.targetAudience) : undefined,
    longDescription: row.longDescription ? String(row.longDescription) : undefined,
    story: row.story ? String(row.story) : undefined,
    coverImageUrl: row.coverImageUrl ? String(row.coverImageUrl) : undefined,
    mediaUrls: Array.isArray(row.mediaUrls) ? (row.mediaUrls as string[]) : [],
    goalAmount: Number(row.goalAmount ?? 0),
    currency: String(row.currency ?? "USD"),
    deadline: String(row.deadline ?? ""),
    donorWallEnabled: Boolean(row.donorWallEnabled),
    raisedAmount: Number(row.raisedAmount ?? 0),
    backersCount: Number(row.backersCount ?? 0),
    status: (row.status as CampaignStatus) ?? "draft",
    creatorId: row.creatorId ? String(row.creatorId) : undefined,
    created_at: row.created_at ? String(row.created_at) : undefined,
    updated_at: row.updated_at ? String(row.updated_at) : undefined,
  };
}

/**
 * Raw database row shape for campaigns. Matches the columns selected by
 * useCampaigns.ts and used by the mapper.
 */
export type CampaignRow = {
  id: string;
  title: string;
  category: string;
  description: string;
  raised: number;
  goal: number;
  backers: number;
  creator_id: string;
  created_at: string;
};

/**
 * Category filter state – a union of the literal category strings plus 'All'.
 */
export type CategoryFilter = typeof CAMPAIGN_CATEGORIES[number] | "All";

// ── Auto-generated by KrossBuild named-export gate ──
// These bindings were imported elsewhere but missing here. Preserved blocks
// are recovered verbatim from the prior version of this file (sticky export
// invariant); unknown names are safe stubs. Replace stubs with real logic.
// [sticky-export] CampaignUpdate — recovered from prior version
export interface CampaignUpdate {
  id: string;
  campaignId: string;
  title: string;
  /** Rich-text (HTML) body — sanitized before rendering. */
  body: string;
  createdAt: string;
}
// [sticky-export] CampaignCurrency — recovered from prior version
export type CampaignCurrency = "USD" | "EUR" | "GBP" | "CAD" | "AUD";
