// AUTO-GENERATED by KrossBuild — points this app at its managed Krossable Cloud backend.
// Do not edit by hand; re-provision the backend from Settings to regenerate.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://kbpgiighshhcrxkuoeaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImticGdpaWdoc2hoY3J4a3VvZWFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQwMDIzODYsImV4cCI6MjA5OTU3ODM4Nn0.hgt7qqPKcDg6p7E6JtXi8oAGTdZ88KyGhOLG7gGyrHc";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  },
});
